version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -d -h 0.0.0.0 /tmp/openapi.yml'
    volumes:
      - ./mock:/tmp:ro
    ports:
      # Serve the mocked API locally as available on port 4010
      - '4010:4010'
