import { AccountWhereUniqueInput } from "../account/AccountWhereUniqueInput";
import { MediaFileWhereUniqueInput } from "../mediaFile/MediaFileWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { OfferWhereUniqueInput } from "../offer/OfferWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { PartConfigurationWhereUniqueInput } from "../partConfiguration/PartConfigurationWhereUniqueInput";
import { PartOnShapeWhereUniqueInput } from "../partOnShape/PartOnShapeWhereUniqueInput";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";

export type PartWhereInput = {
  account?: AccountWhereUniqueInput;
  blueprint?: MediaFileWhereUniqueInput;
  id?: StringFilter;
  offer?: OfferWhereUniqueInput;
  organization?: OrganizationWhereUniqueInput;
  originalBlueprint?: MediaFileWhereUniqueInput;
  originalModel?: MediaFileWhereUniqueInput;
  partConfiguration?: PartConfigurationWhereUniqueInput;
  partOnShape?: PartOnShapeWhereUniqueInput;
  partsCount?: IntNullableFilter;
  process?: StringNullableFilter;
  status?: "draft" | "pending" | "rejected" | "publish";
  stepModel?: MediaFileWhereUniqueInput;
  stlModel?: MediaFileWhereUniqueInput;
  surface?: FloatNullableFilter;
  visible?: BooleanNullableFilter;
  volume?: FloatNullableFilter;
  volumeBoundingBox?: FloatNullableFilter;
  volumeChips?: FloatNullableFilter;
  x?: FloatNullableFilter;
  y?: FloatNullableFilter;
  z?: FloatNullableFilter;
};
