import { Offer } from "../offer/Offer";
import { PartConfiguration } from "../partConfiguration/PartConfiguration";
import { OrderItem } from "../orderItem/OrderItem";
import { ProductionItem } from "../productionItem/ProductionItem";
import { PartMessage } from "../partMessage/PartMessage";
import { PartOnShape } from "../partOnShape/PartOnShape";
import { Production } from "../production/Production";
import { JsonValue } from "type-fest";
import { QuoteItem } from "../quoteItem/QuoteItem";

export type Part = {
  createdAt: Date;
  id: string;
  offersInPart?: Array<Offer>;
  part?: Array<PartConfiguration>;
  partInOrderItem?: Array<OrderItem>;
  partInProduction?: Array<ProductionItem>;
  partMessagesInPart?: Array<PartMessage>;
  partOnShape?: Array<PartOnShape>;
  parts: number | null;
  process: string | null;
  productionsInParts?: Array<Production>;
  quantities: JsonValue | null;
  quoteItem?: Array<QuoteItem>;
  status?: "draft" | "pending" | "rejected" | "publish" | null;
  surface: number | null;
  updatedAt: Date;
  visible: boolean | null;
  volume: number | null;
  volumeBoundingBox: number | null;
  volumeChips: number | null;
  x: number | null;
  y: number | null;
  z: number | null;
};
