import { Offer } from "../offer/Offer";
import { PartConfiguration } from "../partConfiguration/PartConfiguration";
import { PartMessage } from "../partMessage/PartMessage";
import { PartOnShape } from "../partOnShape/PartOnShape";
import { ProductionItem } from "../productionItem/ProductionItem";
import { JsonValue } from "type-fest";
import { Quote } from "../quote/Quote";
import { QuoteItem } from "../quoteItem/QuoteItem";

export type Part = {
  createdAt: Date;
  id: string;
  offer?: Offer | null;
  partConfigurations?: Array<PartConfiguration>;
  partMessages?: Array<PartMessage>;
  partonshape?: PartOnShape | null;
  partOnShapes?: Array<PartOnShape>;
  parts: number | null;
  process: string | null;
  productionItems?: Array<ProductionItem>;
  quantities: JsonValue | null;
  quote?: Quote | null;
  quoteItems?: Array<QuoteItem>;
  status?: "draft" | "pending" | "rejected" | "publish" | null;
  surface: number | null;
  updatedAt: Date;
  visible: boolean | null;
  volume: number | null;
  volumeBoundingBox: number | null;
  volumeChips: number | null;
  x: number | null;
  y: number | null;
  z: number | null;
};
